// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_minimize_abc
S4 cpp_minimize_abc(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_abc(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_abc(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_bat
S4 cpp_minimize_bat(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_bat(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_bat(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_cs
S4 cpp_minimize_cs(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_cs(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_cs(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_ga
S4 cpp_minimize_ga(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_ga(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_ga(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_gsa
S4 cpp_minimize_gsa(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_gsa(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_gsa(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_gwo
S4 cpp_minimize_gwo(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_gwo(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_gwo(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_hs
S4 cpp_minimize_hs(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_hs(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_hs(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_ihs
S4 cpp_minimize_ihs(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_ihs(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_ihs(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_mfo
S4 cpp_minimize_mfo(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_mfo(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_mfo(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_ps
S4 cpp_minimize_ps(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_ps(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_ps(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_sa
S4 cpp_minimize_sa(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_sa(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_sa(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_minimize_woa
S4 cpp_minimize_woa(Function obj_function, List constraints, List parameters, S4 config, S4 opt);
RcppExport SEXP _EmiR_cpp_minimize_woa(SEXP obj_functionSEXP, SEXP constraintsSEXP, SEXP parametersSEXP, SEXP configSEXP, SEXP optSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type obj_function(obj_functionSEXP);
    Rcpp::traits::input_parameter< List >::type constraints(constraintsSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< S4 >::type config(configSEXP);
    Rcpp::traits::input_parameter< S4 >::type opt(optSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_minimize_woa(obj_function, constraints, parameters, config, opt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EmiR_cpp_minimize_abc", (DL_FUNC) &_EmiR_cpp_minimize_abc, 5},
    {"_EmiR_cpp_minimize_bat", (DL_FUNC) &_EmiR_cpp_minimize_bat, 5},
    {"_EmiR_cpp_minimize_cs", (DL_FUNC) &_EmiR_cpp_minimize_cs, 5},
    {"_EmiR_cpp_minimize_ga", (DL_FUNC) &_EmiR_cpp_minimize_ga, 5},
    {"_EmiR_cpp_minimize_gsa", (DL_FUNC) &_EmiR_cpp_minimize_gsa, 5},
    {"_EmiR_cpp_minimize_gwo", (DL_FUNC) &_EmiR_cpp_minimize_gwo, 5},
    {"_EmiR_cpp_minimize_hs", (DL_FUNC) &_EmiR_cpp_minimize_hs, 5},
    {"_EmiR_cpp_minimize_ihs", (DL_FUNC) &_EmiR_cpp_minimize_ihs, 5},
    {"_EmiR_cpp_minimize_mfo", (DL_FUNC) &_EmiR_cpp_minimize_mfo, 5},
    {"_EmiR_cpp_minimize_ps", (DL_FUNC) &_EmiR_cpp_minimize_ps, 5},
    {"_EmiR_cpp_minimize_sa", (DL_FUNC) &_EmiR_cpp_minimize_sa, 5},
    {"_EmiR_cpp_minimize_woa", (DL_FUNC) &_EmiR_cpp_minimize_woa, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_EmiR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
