// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// minimize_PS
void minimize_PS(Function func, List parameters);
RcppExport SEXP _EmiR_minimize_PS(SEXP funcSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type func(funcSEXP);
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    minimize_PS(func, parameters);
    return R_NilValue;
END_RCPP
}
// parameter
S4 parameter(std::string name, double min_val, double max_val);
RcppExport SEXP _EmiR_parameter(SEXP nameSEXP, SEXP min_valSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type min_val(min_valSEXP);
    Rcpp::traits::input_parameter< double >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(parameter(name, min_val, max_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EmiR_minimize_PS", (DL_FUNC) &_EmiR_minimize_PS, 2},
    {"_EmiR_parameter", (DL_FUNC) &_EmiR_parameter, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_EmiR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
