# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Particle Swarm minimization
#'
#' Minimize a cost function using the Particle Swarm (PS) algorithm.
#'
#' @param cost_function cost function to be minimized.
#' @param parameters a list of objects of class `Parameter` the cost function is minimized with respect to.
#' See \link[EmiR]{parameter}.
#' @param config an object of class `PSConfig` with the configuration parameters
#' for the PS algorithm. See \link[EmiR]{config_PS}.
#' @return `minimize_PS` returns an object of class `MinimizationResult`.
#' @examples
#' library(EmiR)
#'
#' eggholder <- function(x) {
#'   value = -(x[2]+47)*sin(sqrt(abs(x[1]/2+x[2]+47)))+x[1]*sin(sqrt(abs(x[1]-(x[2]+47))));
#'   return(value)
#' }
#'
#' x1 <- parameter("x1", -512, 512)
#' x2 <- parameter("x2", -512, 512)
#' l <- list(x1, x2)
#'
#' config <- config_PS(iterations = 250, n_particles = 100)
#' ps <- minimize_PS(cost_function = eggholder,
#'                   parameters = l,
#'                   config = config)
#' print(ps)
#' @export
minimize_PS <- function(cost_function, parameters, config) {
    .Call('_EmiR_minimize_PS', PACKAGE = 'EmiR', cost_function, parameters, config)
}

#' Simulated Annealing minimization
#'
#' Minimize a cost function using the Simulated Annealing (SA) algorithm.
#'
#' @param cost_function cost function to be minimized.
#' @param parameters a list of objects of class `Parameter` the cost function is minimized with respect to.
#' See \link[EmiR]{parameter}.
#' @param config an object of class `SAConfig` with the configuration parameters
#' for the PS algorithm. See \link[EmiR]{config_SA}.
#' @return `minimize_SA` returns an object of class `MinimizationResult`.
#' @examples
#' library(EmiR)
#'
#' eggholder <- function(x) {
#'   value = -(x[2]+47)*sin(sqrt(abs(x[1]/2+x[2]+47)))+x[1]*sin(sqrt(abs(x[1]-(x[2]+47))));
#'   return(value)
#' }
#'
#' x1 <- parameter("x1", -512, 512)
#' x2 <- parameter("x2", -512, 512)
#' l <- list(x1, x2)
#'
#' config <- config_SA(iterations = 250, n_particles = 100)
#' ps <- minimize_SA(cost_function = eggholder,
#'                   parameters = l,
#'                   config = config)
#' print(ps)
#' @export
minimize_SA <- function(cost_function, parameters, config) {
    .Call('_EmiR_minimize_SA', PACKAGE = 'EmiR', cost_function, parameters, config)
}

