# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minimize_PS <- function(cost_function, parameters) {
    .Call(`_EmiR_minimize_PS`, cost_function, parameters)
}

parameter <- function(name, min_val, max_val) {
    .Call(`_EmiR_parameter`, name, min_val, max_val)
}

