# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_minimize_abc <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_abc`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_bat <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_bat`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_cs <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_cs`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_ga <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_ga`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_gsa <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_gsa`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_gwo <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_gwo`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_hs <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_hs`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_ihs <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_ihs`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_mfo <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_mfo`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_ps <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_ps`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_sa <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_sa`, obj_function, constraints, parameters, config, opt)
}

cpp_minimize_woa <- function(obj_function, constraints, parameters, config, opt) {
    .Call(`_EmiR_cpp_minimize_woa`, obj_function, constraints, parameters, config, opt)
}

